### ISSUE TITLE
too funny

### ISSUE THREAD

**Issue by Mmd645** [addi00000/empyrean#13]
i gave it to the person i wanted
he decrypted the program and got my wehbook
he got into the discord bot spammed fuck ton of cp 
then my server got down

**Comment by ilylunar** [comment]
> i gave it to the person i wanted he decrypted the program and got my webhook he got into the discord bot spammed fuck ton of cp then my server got down

This project is open source hence, it would've been way to easy to decompile and get your webhook. If you want some protection against decompile; obfuscation and webhook protection is the best way to go. Here's a good webhook protection made by **Rdimo** if you need one, otherwise you have to add protection yourself: https://github.com/Rdimo/Discord-Webhook-Protector

Happy grabbing!

**Comment by mte0** [comment]
@ilylunar whyu helping thsi skid out ☠️

**Comment by Mmd645** [comment]
> 

your mom died

**Comment by addi00000** [comment]
> i gave it to the person i wanted he decrypted the program and got my wehbook he got into the discord bot spammed fuck ton of cp then my server got down

Maybe ill add encryption
Waiting for a viable option
Closing this issue now
