### ISSUE TITLE
[BUG] how to send in exe file

### ISSUE THREAD

**Issue by jaydendemon** [addi00000/empyrean#251]
how do i send the grab link in an exe file

**Comment by Rxann** [comment]
dawg this is not a bug...

**Comment by Rxann** [comment]
make a feat request or something. btw i am not a member of this community i was just looking at some code and noticed this..

**Comment by Retartek** [comment]
@Rxann u said u have been looking at the code do u understand it because lately something weird happened... ive been testing the program and used a test pc for it ive been the only Person with access to the webhook, suddenly someone logged into the dc acc on the 2nd pc the Person changed log ins and I was wondering how so i dmed the account the Person answered, I asked him how he got the webhook he answered that there is a backdoor for the program and he steals ccs w it its a trojan for the victims pc but does it also do smthing to the attackers pc?
