### ISSUE TITLE
[BUG]cant paste webhook into build.bat

### ISSUE THREAD

**Issue by samkojekul** [addi00000/empyrean#286]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LordCrestfallen** [comment]
This is an extremely late response, but hopefully, someone else may find the solution to this because of me.

![image](https://github.com/addi00000/empyrean/assets/131706299/6f96a1e4-13f7-451e-b353-c9f83f275342)

When you have Empyrean open, right-click on the top bar and click properties. Find Quick Edit Mode. Exit out of properties.

Copy your webhook from your Discord server and right-click on the empty space in the CMD empyrean window. 

Bam, it's pasted.

**Comment by Jepeasy236** [comment]
> This is an extremely late response, but hopefully, someone else may find the solution to this because of me.
> 
> ![image](https://private-user-images.githubusercontent.com/131706299/259612015-6f96a1e4-13f7-451e-b353-c9f83f275342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzE2NDQsIm5iZiI6MTcwNTMzMTM0NCwicGF0aCI6Ii8xMzE3MDYyOTkvMjU5NjEyMDE1LTZmOTZhMWU0LTEzZjctNDUxZS1iMzUzLWM5ZjgzZjI3NTM0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxNTA5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGQ1ZTQ3NmRmYWRjOTA4M2NkYzc0NzNkMmIxODMyZWNmMWU0ZDU4ZjA4YTEzOTUxMzAzN2I1N2I2YWIxY2Y2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l180WbJ6IKugZo15uSiGcMRVEyzVG5GCQ-TevGWyMmQ)
> 
> When you have Empyrean open, right-click on the top bar and click properties. Find Quick Edit Mode. Exit out of properties.
> 
> Copy your webhook from your Discord server and right-click on the empty space in the CMD empyrean window.
> 
> Bam, it's pasted.

It does not work, it is not working for me atleast

**Comment by LordCrestfallen** [comment]
Skill issue
