### ISSUE TITLE
[FEAT.] More browser support & s̴t̴a̴r̴t̴u̴p̴ ̴i̴n̴j̴e̴c̴t̴i̴o̴n̴.

### ISSUE THREAD

**Issue by chiron853** [addi00000/empyrean#34]
opera firefox and chromium passwords and cookies + most important startup and a version without    self.code = decrypted code

**Comment by addi00000** [comment]
1. I am working on adding support for as many browsers as possible.

2. I could add startup but due to the file not being fud it would get deleted (Maybe inject a batch file stub that downloads the file from the internet and runs it?)

3. I don't understand what you mean by "a version without self.code = decrypted code". If you could elaborate that would be appreciated

**Comment by quickdaffy** [comment]
I don't believe the client is FUD anyway, at least after being built.

**Comment by addi00000** [comment]
Not fud, unfortunately. By the time the user restarts their PC defender would've already deleted it. A stub made in batch (.bat) or PowerShell script will be fud and might be able to retrieve the malware from the internet and run it. I don't know where it would be hosted tho. Maybe b64 encoded into the script and rebuilt and ran

**Comment by Foriki** [comment]
i think if the user keeps getting notifcations from windows defender he would prob wipe his pc or know something sus is going on
what about injecting it to discord instead of startup
and make a lite version that would only steal the token so that it wont get flagged by windows defender
https://github.com/Ha1MRX/Discord-Injection
(im not sure if injecting to discord is still a thing)

**Comment by chiron853** [comment]
> 1. I am working on adding support for as many browsers as possible.
> 2. I could add startup but due to the file not being fud it would get deleted (Maybe inject a batch file stub that downloads the file from the internet and runs it?)
> 3. I don't understand what you mean by "a version without self.code = decrypted code". If you could elaborate that would be appreciated

i already know how to make it 2 detections i just need a version with startup and by self.code i mean this so you can add another main.py and it should have startup and the other one doesnt 
![image](https://user-images.githubusercontent.com/68013299/188599313-16ce3ab2-eeb7-4b8d-a346-20986fd1834e.png)

**Comment by addi00000** [comment]
> i think if the user keeps getting notifcations from windows defender he would prob wipe his pc or know something sus is going on
> what about injecting it to discord instead of startup
> and make a lite version that would only steal the token so that it wont get flagged by windows defender
> https://github.com/Ha1MRX/Discord-Injection
> (im not sure if injecting to discord is still a thing)

That is a fork of rdimos injection which is already in the code obfuscated under the injection function

**Comment by chiron853** [comment]
> i think if the user keeps getting notifcations from windows defender he would prob wipe his pc or know something sus is going on what about injecting it to discord instead of startup and make a lite version that would only steal the token so that it wont get flagged by windows defender https://github.com/Ha1MRX/Discord-Injection (im not sure if injecting to discord is still a thing)

bruh just bc someone has a detection doesnt mean you cant add the feature and nobody can make it undetected

**Comment by addi00000** [comment]
Update: startup injection will probably come soon since I just figured out a (hopefully fud) batch file can run executable code stored within a (hopefully fud) .txt file ideally without defender getting pissed. I will keep this issue updated as I move through the development but hopefully, this means I won't have to make the original file fud. maybe in the future, this could just be the way to run it? Idk, we'll see

![image](https://user-images.githubusercontent.com/81730200/188737330-d702ff99-7925-42e8-a40e-d0d8458e5654.png)

**Comment by addi00000** [comment]
Added startup injection :)

![image](https://user-images.githubusercontent.com/81730200/188759952-582002da-f617-43ed-91bb-24446db928a3.png)

**Comment by addi00000** [comment]
Added more browsers and startup so am now closing this issue. Thanks for the suggestions.

**Comment by chiron853** [comment]
> Added startup injection :)
> 
> ![image](https://user-images.githubusercontent.com/81730200/188759952-582002da-f617-43ed-91bb-24446db928a3.png)

no not bat i need exe

**Comment by Smug246** [comment]
goofy font
