### ISSUE TITLE
Bro tf happened to your builder ☠☠(addi raped it 10 times)

### ISSUE THREAD

**Issue by qPhantasm** [addi00000/empyrean#79]
dude tf is wrong with your builder? it's on drugs or something
![image](https://user-images.githubusercontent.com/96620548/200124800-e97d0ce6-1a0a-40f5-bd7a-ad4ce782bf2b.png)
and if you click backspace it makes weird sounds ☠

**Comment by zyzzed** [comment]
fix your fucking goofy ahh builder bro and why does luna has over 25 detections now tf what is happening guys just fix your fucking code, I've found out how to use your autistic crack builder and fucking 8 errors came up please just fix it lmao

**Comment by zyzzed** [comment]
Traceback (most recent call last):
  File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 132, in <module>
    main()
  File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 127, in main
    make_env()()
  File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 64, in __call__
    self.get_src()
  File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 73, in get_src
    subprocess.run(['git', 'clone', 'https://github.com/addi00000/empyrean.git'], cwd=self.build_dir)
  File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
Drücken Sie eine beliebige Taste . . .

**Comment by chiron853** [comment]
> Traceback (most recent call last): File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 132, in main() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 127, in main make_env()() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 64, in **call** self.get_src() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 73, in get_src subprocess.run(['git', 'clone', 'https://github.com/addi00000/empyrean.git'], cwd=self.build_dir) File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden Drücken Sie eine beliebige Taste . . .

i have the same issue

**Comment by zyzzed** [comment]
I can just recommend you a thing. 

Don't use empyrean, only when it's fixed and has not so many detections.



This is my ranking of grabbers. (1 is the best and 5 baddest one but also good..)


1. https://github.com/Smug246/Luna-Token-Grabber (used to be really undetectet but not anymore, really easy to use but has a few bugs while collecting data)

2. https://github.com/Blank-c/Blank-Grabber (collects EVERYTHING but has many detections a few more then luna)

3. https://github.com/unnulled/moonlight-logger (really easy to use but has a few bugs while collecting data)

4. https://github.com/zyzzed/Hazard-Token-Grabber-v2 (copied it, only good as a hidden script in a real python program, e.g. auto-nitro-buy or a nuker)

5. https://github.com/KSCHdsc/BlackCap-Grabber (skidded all his shit and logs users and advertises for this shit now, he is also selling this trash skid thing but it's quite good because he put the best grabbers in it)

6. https://github.com/extatent/PhoenixGrabber (maybe not safe but also very good if the person has his anti-virus disabled and as a one time grab without injection, startup and all that stuff)



**I would recommend you if you start to use moonlight, luna or hazard (you can downlaod the original hazard grabber with a builder from https://cheataway.com/invite)**

(I've checked everything and it looks like it is all really good and safe..)

**Comment by zyzzed** [comment]
> > Traceback (most recent call last): File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 132, in main() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 127, in main make_env()() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 64, in **call** self.get_src() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 73, in get_src subprocess.run(['git', 'clone', 'https://github.com/addi00000/empyrean.git'], cwd=self.build_dir) File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden Drücken Sie eine beliebige Taste . . .
> 
> i have the same issue

I can just recommend you a thing. 

Don't use empyrean, only when it's fixed and has not so many detections.



This is my ranking of grabbers. (1 is the best and 5 baddest one but also good..)


1. https://github.com/Smug246/Luna-Token-Grabber (used to be really undetectet but not anymore, really easy to use but has a few bugs while collecting data)

2. https://github.com/Blank-c/Blank-Grabber (collects EVERYTHING but has many detections a few more then luna)

3. https://github.com/unnulled/moonlight-logger (really easy to use but has a few bugs while collecting data)

4. https://github.com/zyzzed/Hazard-Token-Grabber-v2 (copied it, only good as a hidden script in a real python program, e.g. auto-nitro-buy or a nuker)

5. https://github.com/KSCHdsc/BlackCap-Grabber (skidded all his shit and logs users and advertises for this shit now, he is also selling this trash skid thing but it's quite good because he put the best grabbers in it)

6. https://github.com/extatent/PhoenixGrabber (maybe not safe but also very good if the person has his anti-virus disabled and as a one time grab without injection, startup and all that stuff)



**I would recommend you if you start to use moonlight, luna or hazard (you can downlaod the original hazard grabber with a builder from https://cheataway.com/invite)**

(I've checked everything and it looks like it is all really good and safe..)

**Comment by zyzzed** [comment]
> > Traceback (most recent call last): File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 132, in main() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 127, in main make_env()() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 64, in **call** self.get_src() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 73, in get_src subprocess.run(['git', 'clone', 'https://github.com/addi00000/empyrean.git'], cwd=self.build_dir) File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden Drücken Sie eine beliebige Taste . . .
> 
> i have the same issue

I can just recommend you a thing.

Don't use empyrean, only when it's fixed and has not so many detections.



This is my ranking of grabbers. (1 is the best and 6 baddest one but also good..)


1. https://github.com/Smug246/Luna-Token-Grabber (used to be really undetectet but not anymore, really easy to use but has a few bugs while collecting data)

2. https://github.com/Blank-c/Blank-Grabber (collects EVERYTHING but has many detections a few more then luna)

3. https://github.com/unnulled/moonlight-logger (really easy to use but has a few bugs while collecting data)

4. https://github.com/zyzzed/Hazard-Token-Grabber-v2 (copied it, only good as a hidden script in a real python program, e.g. auto-nitro-buy or a nuker)

5. https://github.com/KSCHdsc/BlackCap-Grabber (skidded all his shit and logs users and advertises for this shit now, he is also selling this trash skid thing but it's quite good because he put the best grabbers in it)

6. https://github.com/extatent/PhoenixGrabber (maybe not safe but also very good if the person has his anti-virus disabled and as a one time grab without injection, startup and all that stuff)



**I would recommend you if you start to use moonlight, luna or hazard (you can downlaod the original hazard grabber with a builder from https://cheataway.com/invite)**

(I've checked everything and it looks like it is all really good and safe..)

**Comment by chiron853** [comment]
> > > Traceback (most recent call last): File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 132, in main() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 127, in main make_env()() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 64, in **call** self.get_src() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 73, in get_src subprocess.run(['git', 'clone', 'https://github.com/addi00000/empyrean.git'], cwd=self.build_dir) File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden Drücken Sie eine beliebige Taste . . .
> > 
> > 
> > i have the same issue
> 
> I can just recommend you a thing.
> 
> Don't use empyrean, only when it's fixed and has not so many detections.
> 
> This is my ranking of grabbers. (1 is the best and 6 baddest one but also good..)
> 
> 1. https://github.com/Smug246/Luna-Token-Grabber (used to be really undetectet but not anymore, really easy to use but has a few bugs while collecting data)
> 2. https://github.com/Blank-c/Blank-Grabber (collects EVERYTHING but has many detections a few more then luna)
> 3. https://github.com/unnulled/moonlight-logger (really easy to use but has a few bugs while collecting data)
> 4. https://github.com/zyzzed/Hazard-Token-Grabber-v2 (copied it, only good as a hidden script in a real python program, e.g. auto-nitro-buy or a nuker)
> 5. https://github.com/KSCHdsc/BlackCap-Grabber (skidded all his shit and logs users and advertises for this shit now, he is also selling this trash skid thing but it's quite good because he put the best grabbers in it)
> 6. https://github.com/extatent/PhoenixGrabber (maybe not safe but also very good if the person has his anti-virus disabled and as a one time grab without injection, startup and all that stuff)
> 
> **I would recommend you if you start to use moonlight, luna or hazard (you can downlaod the original hazard grabber with a builder from https://cheataway.com/invite)**
> 
> (I've checked everything and it looks like it is all really good and safe..)

i know how to make it fud i only need a working one with most features

**Comment by zyzzed** [comment]
> > > > Traceback (most recent call last): File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 132, in main() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 127, in main make_env()() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 64, in **call** self.get_src() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 73, in get_src subprocess.run(['git', 'clone', 'https://github.com/addi00000/empyrean.git'], cwd=self.build_dir) File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden Drücken Sie eine beliebige Taste . . .
> > > 
> > > 
> > > i have the same issue
> > 
> > 
> > I can just recommend you a thing.
> > Don't use empyrean, only when it's fixed and has not so many detections.
> > This is my ranking of grabbers. (1 is the best and 6 baddest one but also good..)
> > 
> > 1. https://github.com/Smug246/Luna-Token-Grabber (used to be really undetectet but not anymore, really easy to use but has a few bugs while collecting data)
> > 2. https://github.com/Blank-c/Blank-Grabber (collects EVERYTHING but has many detections a few more then luna)
> > 3. https://github.com/unnulled/moonlight-logger (really easy to use but has a few bugs while collecting data)
> > 4. https://github.com/zyzzed/Hazard-Token-Grabber-v2 (copied it, only good as a hidden script in a real python program, e.g. auto-nitro-buy or a nuker)
> > 5. https://github.com/KSCHdsc/BlackCap-Grabber (skidded all his shit and logs users and advertises for this shit now, he is also selling this trash skid thing but it's quite good because he put the best grabbers in it)
> > 6. https://github.com/extatent/PhoenixGrabber (maybe not safe but also very good if the person has his anti-virus disabled and as a one time grab without injection, startup and all that stuff)
> > 
> > **I would recommend you if you start to use moonlight, luna or hazard (you can downlaod the original hazard grabber with a builder from https://cheataway.com/invite)**
> > (I've checked everything and it looks like it is all really good and safe..)
> 
> i know how to make it fud i only need a working one with most features

Use Luna Grabber

**Comment by RGB-PANZER** [comment]
> 
How to make it fud?

**Comment by RGB-PANZER** [comment]
> > > > Traceback (most recent call last): File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 132, in main() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 127, in main make_env()() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 64, in **call** self.get_src() File "C:\Users\CENSORED\Documents\Tools\Discord-Tools\Token-Grabber\empyrean-main\builder.py", line 73, in get_src subprocess.run(['git', 'clone', 'https://github.com/addi00000/empyrean.git'], cwd=self.build_dir) File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\CENSORED\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden Drücken Sie eine beliebige Taste . . .
> > > 
> > > 
> > > i have the same issue
> > 
> > 
> > I can just recommend you a thing.
> > Don't use empyrean, only when it's fixed and has not so many detections.
> > This is my ranking of grabbers. (1 is the best and 6 baddest one but also good..)
> > 
> > 1. https://github.com/Smug246/Luna-Token-Grabber (used to be really undetectet but not anymore, really easy to use but has a few bugs while collecting data)
> > 2. https://github.com/Blank-c/Blank-Grabber (collects EVERYTHING but has many detections a few more then luna)
> > 3. https://github.com/unnulled/moonlight-logger (really easy to use but has a few bugs while collecting data)
> > 4. https://github.com/zyzzed/Hazard-Token-Grabber-v2 (copied it, only good as a hidden script in a real python program, e.g. auto-nitro-buy or a nuker)
> > 5. https://github.com/KSCHdsc/BlackCap-Grabber (skidded all his shit and logs users and advertises for this shit now, he is also selling this trash skid thing but it's quite good because he put the best grabbers in it)
> > 6. https://github.com/extatent/PhoenixGrabber (maybe not safe but also very good if the person has his anti-virus disabled and as a one time grab without injection, startup and all that stuff)
> > 
> > **I would recommend you if you start to use moonlight, luna or hazard (you can downlaod the original hazard grabber with a builder from https://cheataway.com/invite)**
> > (I've checked everything and it looks like it is all really good and safe..)
> 
> i know how to make it fud i only need a working one with most features

How to make it Fud?

**Comment by addi00000** [comment]
In cmd you can right click the top bar and find paste to paste the webhook. other than that this issue is skidish

closing
